#!/bin/bash
# 
#   fwbootstrap - enter to a Frugalware chroot
#  
#   Copyright (c) 2005 Miklos Vajna <vmiklos@frugalware.org>
#  
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
# 
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#  
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, 
#   USA.
#

USE_COLOR="n"

# Frugalware extensions to makepkg
[ -e /usr/lib/frugalware/fwmakepkg ] && . /usr/lib/frugalware/fwmakepkg

# source Arch's abs.conf if it's present
[ -f /etc/abs/abs.conf ] && source /etc/abs/abs.conf

# makepkg configuration
[ -f /etc/makepkg.conf ] && source /etc/makepkg.conf

CHROOTDIR=$1

### SUBROUTINES ###

plain() {
	if [ "$USE_COLOR" = "Y" -o "$USE_COLOR" = "y" ]; then
		echo -e "    \033[1;1m$1\033[1;0m" >&2
	else
		echo "    $1" >&2
	fi
}
msg() {
	if [ "$USE_COLOR" = "Y" -o "$USE_COLOR" = "y" ]; then
		echo -e "\033[1;32m==>\033[1;0m \033[1;1m$1\033[1;0m" >&2
	else
		echo "==> $1" >&2
	fi
}
warning() {
	if [ "$USE_COLOR" = "Y" -o "$USE_COLOR" = "y" ]; then
		echo -e "\033[1;33m==> WARNING:\033[1;0m \033[1;1m$1\033[1;0m" >&2
	else
		echo "==> WARNING: $1" >&2
	fi
}
error() {
	if [ "$USE_COLOR" = "Y" -o "$USE_COLOR" = "y" ]; then
		echo -e "\033[1;31m==> ERROR:\033[1;0m \033[1;1m$1\033[1;0m" >&2
	else
		echo "==> ERROR: $1" >&2
	fi
}

chroot_umount() {
    msg "Attempting to umount chroot directories..."
    umount $CHROOTDIR/proc >/dev/null &
    umount $CHROOTDIR/sys >/dev/null &
    umount $CHROOTDIR/dev >/dev/null &
    if [ "$?" != "0" ]; then
	error "An error occurred while attempting to umount chroot directories."
	exit 1
    fi
    msg "Successfully umounted chroot directories."
}

chroot_mount() {
    msg "Attempting to mount chroot directories..."
    mount -t proc none $CHROOTDIR/proc >/dev/null &
    mount -t sysfs none $CHROOTDIR/sys >/dev/null &
    mount -o bind /dev $CHROOTDIR/dev >/dev/null &
    if [ "$?" != "0" ]; then
	error "An error occurred while attempting to mount chroot directories."
	exit 1
    fi
    msg "Successfully mounted chroot directories."
}

# Enter chroot environment.
if [ "`id -u`" != 0 ]; then
error "Entering chroot environment as an unprivileged user is not possible."
	exit 1
fi
if [ ! -d "$CHROOTDIR" ]; then
	error "The $CHROOTDIR directory does not exists."
	exit 1
fi

if [ -e $CHROOTDIR/var/tmp/fst/lock ]; then
	error "Somebody already building in this chroot."
	plain "If you're sure makepkg is not already running, you"
	plain "can remove $CHROOTDIR/var/tmp/fst/lock."
	exit 1
else
	touch $CHROOTDIR/var/tmp/fst/lock
fi

chroot_mount

msg "Copying config files to chroot"
cp -pf /etc/resolv.conf $CHROOTDIR/etc >/dev/null &
cp -pf /etc/passwd $CHROOTDIR/etc >/dev/null &
cp -pf /etc/shadow $CHROOTDIR/etc >/dev/null &
cp -pf /etc/group $CHROOTDIR/etc >/dev/null &
cp -pf /etc/ld.so.conf $CHROOTDIR/etc >/dev/null &
cp -pf /etc/hosts $CHROOTDIR/etc > /dev/null &
cp -pf /etc/sudoers $CHROOTDIR/etc > /dev/null &
cp -Ppf /etc/localtime $CHROOTDIR/etc >/dev/null &
cp -pf /etc/services $CHROOTDIR/etc > /dev/null &
if [ "$?" != "0" ]; then
	error "An error occurred while attempting to copy config files to chroot."
	chroot_umount
	exit 1
fi

if [ ! -x  /usr/sbin/chroot ]; then
	error "chroot was not found."
else
	msg "Entering chroot environment"
	/usr/sbin/chroot $CHROOTDIR /bin/bash --login
fi

chroot_umount
rm -f $CHROOTDIR/var/tmp/fst/lock
